CREATE TABLE APP.Product(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	code VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	init_q FLOAT DEFAULT 0,
	init_pq FLOAT DEFAULT 0,
	init_p INT DEFAULT NULL,
	last_p INT DEFAULT NULL,
	last_code VARCHAR(15) DEFAULT NULL,
	CONSTRAINT PUNQ UNIQUE (code, name)
);

CREATE TABLE APP.Supplier(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	code VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	is_main SMALLINT NOT NULL DEFAULT 0,
	lim FLOAT DEFAULT NULL,
	is_full SMALLINT NOT NULL DEFAULT 1,
	group_id INT NOT NULL DEFAULT 1,
	price_percent FLOAT NOT NULL DEFAULT 0,
	CONSTRAINT SUNQ UNIQUE (code, name)
);

CREATE TABLE APP.Supplier_Product(
	supplier_id INT NOT NULL REFERENCES APP.Supplier(id),
	product_id INT NOT NULL REFERENCES APP.Product(id),
	CONSTRAINT S_PUNQ UNIQUE (supplier_id, product_id)
);

CREATE TABLE APP.Customer(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	code VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	CONSTRAINT CUNQ UNIQUE (code, name)
);

CREATE TABLE APP.Staff(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	position VARCHAR(30) NOT NULL,
	base_wage INT NOT NULL DEFAULT 0,
	sub_wage INT NOT NULL DEFAULT 0,
	base_eff INT NOT NULL DEFAULT 0,
	pob INT NOT NULL DEFAULT 0,
	insurance INT NOT NULL DEFAULT 0,
	imprest INT NOT NULL DEFAULT 0,
	day_off FLOAT NOT NULL DEFAULT 0,
	holiday INT NOT NULL DEFAULT 0
);

CREATE TABLE APP.Tax_Connection(
	product_name VARCHAR(100) UNIQUE NOT NULL,
	tax_name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE APP.PtoPP(
	code VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	promoCode VARCHAR(50) NOT NULL,
	promoName VARCHAR(100) NOT NULL,
	CONSTRAINT CODEUNQ UNIQUE (code, name)
);

CREATE TABLE APP.Conn(
	code VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	newCode VARCHAR(50) NOT NULL,
	newName VARCHAR(100) NOT NULL,
	CONSTRAINT CONUNQ UNIQUE (code, name)
);

CREATE TABLE APP.NonSplitProduct(
	code VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	CONSTRAINT SPLITUNQ UNIQUE (code, name)
);

CREATE TABLE APP.Buy(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	code VARCHAR(15) NOT NULL,
	day DATE NOT NULL,
	supplier_id INT NOT NULL REFERENCES APP.Supplier(id),
	CONSTRAINT BUYUNQ UNIQUE (code, day)
);

CREATE TABLE APP.RBuy(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	code VARCHAR(15) NOT NULL,
	day DATE NOT NULL,
	supplier_id INT NOT NULL REFERENCES APP.Supplier(id),
	CONSTRAINT RBUYUNQ UNIQUE (code, day)
);

CREATE TABLE APP.Sell(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	code VARCHAR(15) NOT NULL,
	day DATE NOT NULL,
	customer_id INT NOT NULL REFERENCES APP.Customer(id),
	CONSTRAINT SELLUNQ UNIQUE (code, day)
);

CREATE TABLE APP.RSell(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	code VARCHAR(15) NOT NULL,
	day DATE NOT NULL,
	customer_id INT NOT NULL REFERENCES APP.Customer(id),
	CONSTRAINT RSELLUNQ UNIQUE (code, day)
);

CREATE TABLE APP.Buy_Product(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	buy_id INT NOT NULL REFERENCES APP.Buy(id),
	product_id INT NOT NULL REFERENCES APP.Product(id),
	q FLOAT NOT NULL,
	pq FLOAT NOT NULL,
	cost INT NOT NULL,
	CONSTRAINT ABPUNQ UNIQUE (buy_id, product_id)
);

CREATE TABLE APP.RBuy_Product(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	rbuy_id INT NOT NULL REFERENCES APP.RBuy(id),
	product_id INT NOT NULL REFERENCES APP.Product(id),
	q FLOAT NOT NULL,
	pq FLOAT NOT NULL,
	cost INT NOT NULL,
	CONSTRAINT ARBPUNQ UNIQUE (rbuy_id, product_id)
);

CREATE TABLE APP.Sell_Product(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	sell_id INT NOT NULL REFERENCES APP.Sell(id),
	product_id INT NOT NULL REFERENCES APP.Product(id),
	q FLOAT NOT NULL,
	pq FLOAT NOT NULL,
	cost INT NOT NULL,
	CONSTRAINT ASPUNQ UNIQUE (sell_id, product_id)
);

CREATE TABLE APP.RSell_Product(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1) PRIMARY KEY,
	rsell_id INT NOT NULL REFERENCES APP.RSell(id),
	product_id INT NOT NULL REFERENCES APP.Product(id),
	q FLOAT NOT NULL,
	pq FLOAT NOT NULL,
	cost INT NOT NULL,
	last_p INT DEFAULT NULL,
	last_code VARCHAR(15) DEFAULT NULL,
	CONSTRAINT ARSPUNQ UNIQUE (rsell_id, product_id)
);

CREATE SCHEMA APPDATE;

CREATE TABLE APPDATE.Product_Status(
	product_id INT NOT NULL REFERENCES APP.Product(id),
	code VARCHAR(15) NOT NULL,
	q FLOAT NOT NULL,
	pq FLOAT NOT NULL,
	CONSTRAINT PSTUNQ UNIQUE (product_id, code)
);

CREATE TABLE APPDATE.Sell_Profit(
	sell_id INT UNIQUE NOT NULL REFERENCES APP.Sell_Product(id),
	sp INT NOT NULL,
	bp INT NOT NULL,
	rq FLOAT NOT NULL DEFAULT 0
);

CREATE TABLE APPDATE.Sell_Status(
	sell_id INT UNIQUE NOT NULL REFERENCES APP.Sell_Product(id),
	q FLOAT NOT NULL,
	pq FLOAT NOT NULL
);

CREATE TABLE APPDATE.RSell_Status(
	rsell_id INT UNIQUE NOT NULL REFERENCES APP.RSell_Product(id),
	q FLOAT NOT NULL,
	pq FLOAT NOT NULL
);

CREATE TABLE APPDATE.Buy_Status(
	buy_id INT UNIQUE NOT NULL REFERENCES APP.Buy_Product(id),
	q FLOAT NOT NULL,
	pq FLOAT NOT NULL
);

CREATE TABLE APPDATE.RBuy_Status(
	rbuy_id INT UNIQUE NOT NULL REFERENCES APP.RBuy_Product(id),
	q FLOAT NOT NULL,
	pq FLOAT NOT NULL
);

CREATE TABLE APPDATE.RSell_Profit(
	rsell_id INT UNIQUE NOT NULL REFERENCES APP.RSell_Product(id),
	q FLOAT NOT NULL,
	sp INT NOT NULL,
	bp INT NOT NULL
);

CREATE TABLE APPDATE.RSell_Sell(
	rsell_id INT NOT NULL REFERENCES APP.RSell_Product(id),
	sell_id INT NOT NULL REFERENCES APP.Sell_Product(id),
	q FLOAT NOT NULL,
	CONSTRAINT RSSUNQ UNIQUE (rsell_id, sell_id)
);

CREATE TABLE APPDATE.Sell_History(
	sell_id INT NOT NULL REFERENCES APP.Sell_Product(id),
	code VARCHAR(15) NOT NULL,
	q FLOAT NOT NULL,
	CONSTRAINT SHUNQ UNIQUE (sell_id, code)
);
